### ISSUE TITLE
[Bug] favicon Not Found when Launching `Gradio`

### ISSUE THREAD

**Issue by 1chooo** [1chooo/simple-ai#110]
When launching the `/gradio/` playground, we are unable to locate the `favicon.ico` file. We must conduct research on how to customize the icon on the **"Gradio"** page.
```console
INFO:     127.0.0.1:xxxxx - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

**Comment by kshitiz305** [comment]
I wish to contribute to the repo. Please assign it to me.

**Comment by 1chooo** [comment]
Hey @kshitiz305 
Thank you very much for your assistance. At this stage, we indeed need more developers to contribute to our project. You can directly **fork** this project, and if you manage to fix this bug, please submit it through a **Pull Request**. I will review it, and if there are no issues, I will merge it into the project. I would like to express my gratitude once again. If it's convenient for you, please consider clicking the star to support us, making this project even better and more complete.

**Comment by 1chooo** [comment]
Hey, @kshitiz305 

Remember to set the `upstream`
```shell
$ git remote add upstream git@github.com:1chooo/simple-ai.git

$ git remote -v
origin  git@github.com:<your_user_name>/simple-ai.git (fetch)
origin  git@github.com:<your_user_name>/simple-ai.git (push)
upstream        git@github.com:1chooo/simple-ai.git (fetch)
upstream        git@github.com:1chooo/simple-ai.git (push)
```

**Comment by kshitiz305** [comment]
are we using linux or windows

**Comment by 1chooo** [comment]
We use Linux and MacOS; however windows still work!

**Comment by kshitiz305** [comment]
![image](https://github.com/1chooo/simple-ai/assets/38988779/1860f25a-a007-4f7a-a0e8-c330dd675ff6)

**Comment by 1chooo** [comment]
That's it!!! You fixed it!

**Comment by 1chooo** [comment]
Hi @kshitiz305, it's been a while. I wanted to ask, what tool or program did you use before to convert images into the `.ico` format?
