### ISSUE TITLE
[Bug] x and y-axis labels incorrect

### ISSUE THREAD

**Issue by 1chooo** [1chooo/simple-ai#41]
**Descriptions**
Currently, the plot's x and y-axis labels in preprocessing are incorrect; they should display all the information from the table.

**Screenshots**
<img width="623" alt="Screen Shot 2023-08-30 at 9 16 09 PM" src="https://github.com/1chooo/simple-ai/assets/94162591/4b63458b-3ac9-4bd7-8b9f-53bbd57f1dba">
<img width="621" alt="Screen Shot 2023-08-30 at 9 16 14 PM" src="https://github.com/1chooo/simple-ai/assets/94162591/86797e3d-207b-485c-b5ec-41fec1c952aa">

**Comment by ReeveWu** [comment]
I have already written the function to retrieve the X columns names of each dataset in `Load.py`. You can use the following code to obtain it:
```py
from Refinaid.Action.Load import get_dataset_x_columns
X_columns = get_dataset_x_columns("<dataset name>")
```

**Comment by VincentLi1216** [comment]
Sure, I am working on it.

**Comment by 1chooo** [comment]
Hi @VincentLi1216 
Thank you for your valuable assistance. However, it might be beneficial to wait for me to resolve the issue related to the '**update**' method, as demonstrated in the following code. Our future coding approach aims to utilize the '**<update_goal>**' concept to refresh objects, enhancing the expandability of our code.
```py
def update_parameters(dataset):
    if dataset == "Titanic":
        parameters = ["Param1", "Param2", "Param3"]
    elif dataset == "Diabetes":
        parameters = ["ParamA", "ParamB", "ParamC"]
    elif dataset == "House Prices":
        parameters = ["ParamX", "ParamY", "ParamZ"]
    else:
        parameters = []
    return parameters
```

**Comment by 1chooo** [comment]
Since the current `main.py` has undergone refactoring, this functionality needs to be reintegrated. The integration should take place within the `Refinaid.gui` module.

**Comment by ReeveWu** [comment]
@1chooo  This issue seems to have already been resolved!
